/* Midori High V2 — client compatible with the V2 schema currently installed. */
const { createClient } = window.supabase;
const cfg = window.MIDORI_CONFIG;
const sb = createClient(cfg.SUPABASE_URL, cfg.SUPABASE_KEY);
const $ = (s) => document.querySelector(s);
const esc = (v) => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const page = location.pathname.split('/').pop() || 'index.html';
const defs = {
 'dashboard.html': ['Tableau de bord','Vue générale',null],
 'students.html':['Profils','Gestion des profils','profiles'], 'profiles.html':['Profils','Profils liés aux personnes','profiles'],
 'profile-management.html':['Gestion des profils','Profils et accès','profiles'], 'profile.html':['Mon profil','Informations du profil','profiles'],
 'classes.html':['Classes','Créer et gérer les classes','school_classes'], 'clubs.html':['Clubs','Créer et gérer les clubs','school_clubs'],
 'subjects.html':['Matières','Créer et gérer les matières','school_subjects'], 'timetable.html':['Cours / planning','Cours programmés','school_courses'],
 'prof-timetable.html':['Planning professeur','Cours programmés','school_courses'], 'student-timetable.html':['Mon planning','Cours programmés','school_courses'],
 'grades.html':['Notes','Notes scolaires','school_grades'], 'prof-grades.html':['Notes','Notes scolaires','school_grades'], 'student-grades.html':['Mes notes','Notes scolaires','school_grades'],
 'attendance.html':['Présences','Suivi des présences','school_attendance'], 'prof-attendance.html':['Présences','Suivi des présences','school_attendance'], 'student-attendance.html':['Mes présences','Suivi des présences','school_attendance'], 'absences.html':['Absences','Suivi des présences','school_attendance'],
 'homework.html':['Devoirs','Devoirs de la classe','school_homework'], 'prof-homework.html':['Devoirs','Devoirs de la classe','school_homework'], 'student-homework.html':['Mes devoirs','Devoirs de la classe','school_homework'],
 'prof-resources.html':['Ressources','Ressources pédagogiques','school_resources'], 'announcements.html':['Annonces','Les annonces sont disponibles dans les ressources V2 après configuration.','school_resources'],
 'professors.html':['Équipe pédagogique','Affectations des membres du personnel','school_staff_assignments'], 'supervisors.html':['Surveillants','Affectations du personnel','school_staff_assignments'],
 'access.html':['Accès','Comptes et accès','profiles'], 'wl.html':['Registre WL','Registre des personnes validées','wl_registry'], 'wl-import.html':['Import WL','Les imports historiques ne sont pas repris dans cette V2.','midori_people'],
 'migration.html':['Migration','La migration des anciens profils est désactivée : le projet V2 démarre vide.','profiles'], 'messages.html':['Messagerie','Messagerie interne V2','school_messages'],
 'homework-submissions.html':['Rendus des devoirs','Suivi des rendus','school_homework_submissions'], 'points.html':['Points RP','Registre des points RP','school_points'], 'student-points.html':['Mes points RP','Registre des points RP','school_points'],
 'discipline.html':['Discipline','Registre des sanctions RP','school_sanctions'], 'events.html':['Événements','Événements de l’établissement','school_events'], 'logs.html':['Journal','Journal d’activité','school_activity_logs'],
 'student-profile.html':['Fiche élève','Fiches élèves','profiles'], 'student-space.html':['Espace élève','Vue élève','profiles'], 'prof-space.html':['Espace professeur','Vue professeur','profiles'], 'supervisor-space.html':['Espace surveillant','Vue surveillant','profiles'], 'supervisor-absences.html':['Absences','Suivi des présences','school_attendance'], 'supervisor-reports.html':['Rapports','Rapports de surveillance','school_supervisor_reports'], 'supervisor-sanctions.html':['Sanctions','Registre des sanctions RP','school_sanctions'],
 'student-clubs.html':['Mes clubs','Clubs','school_clubs'], 'student-appointments.html':['Mes rendez-vous','Rendez-vous RP','school_appointments'], 'psych-space.html':['Espace psychologue','Affectations du personnel','school_staff_assignments'], 'psych-appointments.html':['Rendez-vous','Rendez-vous RP','school_appointments'], 'psych-records.html':['Dossiers psychologue','Les dossiers confidentiels ne sont pas configurés dans V2.',''], 'nurse-space.html':['Infirmerie','Affectations du personnel','school_staff_assignments'], 'nurse-appointments.html':['Rendez-vous infirmerie','Rendez-vous RP','school_appointments'], 'nurse-records.html':['Dossiers infirmerie','Les dossiers confidentiels ne sont pas configurés dans V2.',''],
 'student.html':['Espace élève','Vue élève','profiles'], 'professor.html':['Espace professeur','Vue professeur','profiles'], 'supervisors.html':['Surveillants','Affectations du personnel','school_staff_assignments'], 'nurse-records.html':['Dossiers infirmerie','Dossiers confidentiels non configurés dans V2.','']
};
const fields = {
 school_classes:[['name','Nom','text'],['school_year','Année scolaire','text']],
 school_clubs:[['name','Nom du club','text'],['description','Description','textarea']],
 school_subjects:[['name','Nom de la matière','text'],['description','Description','textarea']],
 school_courses:[['title','Titre','text'],['description','Description','textarea'],['scheduled_at','Date et heure','datetime-local'],['class_id','ID classe (facultatif)','text'],['subject_id','ID matière (facultatif)','text']],
 school_homework:[['title','Titre','text'],['description','Consignes','textarea'],['due_at','À rendre le','datetime-local'],['class_id','ID classe','text'],['subject_id','ID matière','text']],
 school_resources:[['title','Titre','text'],['description','Description','textarea'],['resource_url','Lien','url'],['class_id','ID classe (facultatif)','text'],['subject_id','ID matière (facultatif)','text']],
 school_grades:[['profile_id','ID profil','text'],['subject_id','ID matière','text'],['course_id','ID cours (facultatif)','text'],['grade','Note','number'],['max_grade','Sur','number'],['comment','Commentaire','text']],
 school_attendance:[['profile_id','ID profil','text'],['course_id','ID cours (facultatif)','text'],['attendance_date','Date','date'],['status','Statut (present/absent/late/excused)','text']],
 school_staff_assignments:[['profile_id','ID profil','text'],['function_name','Fonction (proviseur/proviseur_adjoint/cpe/professeur/surveillant/infirmiere/psychologue)','text']],
 profiles:[['person_id','ID personne liée (UUID)','text'],['full_name','Nom affiché','text'],['school_email','E-mail scolaire','email'],['profile_kind','Type (student/staff)','text'],['role','Rôle','text'],['access_status','Accès (pending/active/suspended)','text'],['active','Actif (true/false)','text']],
 midori_people:[['discord_username','Pseudo Discord','text'],['roblox_username','Pseudo Roblox','text'],['active','Actif (true/false)','text']],
 school_messages:[['sender_profile_id','ID profil expéditeur','text'],['recipient_profile_id','ID profil destinataire','text'],['subject','Objet','text'],['body','Message','textarea'],['is_read','Lu (true/false)','text']],
 school_message_attachments:[['message_id','ID message','text'],['file_name','Nom du fichier','text'],['file_url','Lien du fichier','url']],
 school_homework_submissions:[['homework_id','ID devoir','text'],['profile_id','ID profil élève','text'],['submission_text','Réponse / lien','textarea'],['status','Statut','text'],['feedback','Retour du professeur','textarea']],
 school_points:[['profile_id','ID profil','text'],['points','Points (+/-)','number'],['reason','Motif','text'],['awarded_by','ID profil responsable','text']],
 school_sanctions:[['profile_id','ID profil concerné','text'],['sanction_type','Type de sanction','text'],['reason','Motif','textarea'],['issued_by','ID profil responsable','text'],['issued_at','Date','datetime-local'],['status','Statut','text']],
 school_events:[['title','Titre','text'],['description','Description','textarea'],['starts_at','Début','datetime-local'],['ends_at','Fin','datetime-local'],['location','Lieu','text']],
 school_activity_logs:[['actor_profile_id','ID profil acteur','text'],['action','Action','text'],['target_type','Type de cible','text'],['target_id','ID cible','text'],['details','Détails','textarea']],
 school_appointments:[['profile_id','ID profil concerné','text'],['staff_profile_id','ID profil personnel','text'],['appointment_type','Type de rendez-vous','text'],['scheduled_at','Date et heure','datetime-local'],['reason','Motif','textarea'],['status','Statut','text']],
 school_supervisor_reports:[['profile_id','ID profil concerné','text'],['author_profile_id','ID profil rédacteur','text'],['report_type','Type de rapport','text'],['description','Description','textarea'],['reported_at','Date','datetime-local'],['status','Statut','text']],
 wl_registry:[['discord_username','Pseudo Discord','text'],['roblox_username','Pseudo Roblox','text'],['display_name','Nom RP','text'],['validated_by','Validé par','text'],['status','Statut (validated/revoked)','text'],['notes','Notes','textarea']]
};
function shell(title, subtitle, body){ document.body.innerHTML=`<header class="mh-header"><div><strong>🎐 Midori High</strong><small>Portail administratif V2</small></div><button id="logout" class="btn secondary">Déconnexion</button></header><main class="mh-main"><h1>${esc(title)}</h1><p class="muted">${esc(subtitle||'')}</p><nav class="mh-nav"><a href="dashboard.html">Accueil</a><a href="students.html">Profils</a><a href="classes.html">Classes</a><a href="subjects.html">Matières</a><a href="timetable.html">Cours</a><a href="clubs.html">Clubs</a><a href="attendance.html">Présences</a><a href="grades.html">Notes</a><a href="homework.html">Devoirs</a><a href="professors.html">Personnel</a><a href="wl.html">Registre WL</a></nav><section id="app">${body||''}</section><footer>Midori High V2 · Projet de rôle-play</footer></main>`; $('#logout')?.addEventListener('click',async()=>{await sb.auth.signOut();location.href='index.html'}); }
function login(){document.body.innerHTML=`<main class="mh-login"><section class="mh-login-card"><div class="mh-brand">🎐</div><h1>Midori High</h1><p>Portail administratif V2</p><form id="login"><label>E-mail utilisé pour le compte Supabase<input name="email" type="email" required autocomplete="username"></label><label>Mot de passe<input name="password" type="password" required autocomplete="current-password"></label><p id="error" class="error" hidden></p><button class="btn primary" type="submit">Se connecter</button></form><small>Utilise l’adresse réelle du compte créé dans Supabase Auth, pas l’adresse RP affichée sur le profil.</small></section></main>`;$('#login').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target);let {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error){$('#error').hidden=false;$('#error').textContent=error.message;return}location.href='dashboard.html'};}
async function getProfile(user){
  // Resolve auth -> person -> profile in two queries. This avoids relying on
  // PostgREST embedded-relationship syntax and matches the installed V2 schema.
  const personResult = await sb.from('midori_people')
    .select('id, active')
    .eq('auth_user_id', user.id)
    .maybeSingle();
  if (personResult.error) throw personResult.error;
  if (!personResult.data || personResult.data.active === false) {
    throw new Error('Aucune personne Midori High active n’est liée à ce compte.');
  }
  const profileResult = await sb.from('profiles')
    .select('*')
    .eq('person_id', personResult.data.id)
    .eq('active', true)
    .maybeSingle();
  if (profileResult.error) throw profileResult.error;
  if (!profileResult.data) {
    throw new Error('Aucun profil Midori High actif n’est lié à cette personne.');
  }
  const profile = profileResult.data;
  // Normalize the role name used by the administrator account.
  if (profile.role === 'administrateur') profile.role = 'admin';
  return profile;
}
async function listTable(table){const {data,error}=await sb.from(table).select('*').limit(200);if(error)throw error;return data||[];}
function renderTable(table,rows){if(!rows.length)return '<p class="empty">Aucune donnée pour le moment.</p>';const keys=Object.keys(rows[0]).filter(k=>!['auth_user_id'].includes(k)).slice(0,7);return `<div class="table-wrap"><table><thead><tr>${keys.map(k=>`<th>${esc(k)}</th>`).join('')}<th>Action</th></tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${esc(typeof r[k]==='object'?JSON.stringify(r[k]):r[k])}</td>`).join('')}<td>${r.id?`<button class="btn danger small" data-del="${esc(r.id)}">Supprimer</button>`:''}</td></tr>`).join('')}</tbody></table></div>`;}
async function renderData(table,title){const app=$('#app');if(!table){app.innerHTML=`<article class="card"><h2>Module à compléter</h2><p>Cette fonction historique n’est pas encore disponible dans le schéma V2. Les données ne sont pas supprimées ; ce module est simplement désactivé dans cette version.</p></article>`;return;}let rows=await listTable(table);let canAdd=!!fields[table];let form=canAdd?`<details class="card"><summary>＋ Ajouter une entrée</summary><form id="create" class="mh-form">${fields[table].map(([k,label,type])=>`<label>${esc(label)}${type==='textarea'?`<textarea name="${k}"></textarea>`:`<input name="${k}" type="${type}" ${['name','title','full_name','school_email','profile_kind','role','function_name','person_id','profile_id','grade','max_grade','attendance_date','status'].includes(k)?'required':''}>`}</label>`).join('')}<button class="btn primary">Enregistrer</button></form></details>`:'';app.innerHTML=`<div class="card"><div class="mh-row"><h2>${esc(title)}</h2><button id="refresh" class="btn secondary">Actualiser</button></div><p>${rows.length} entrée(s) affichée(s), maximum 200.</p>${form}<div id="data">${renderTable(table,rows)}</div></div>`;$('#refresh').onclick=()=>renderData(table,title);$('#create')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);const obj={};for(const [k,v] of f.entries()){if(v==='')continue;obj[k]=['grade','max_grade','points'].includes(k)?Number(v):(['active','is_read'].includes(k)?v==='true':v);}const {error}=await sb.from(table).insert(obj);if(error){alert('Échec : '+error.message);return;}await renderData(table,title);});app.querySelectorAll('[data-del]').forEach(b=>b.onclick=async()=>{if(!confirm('Supprimer cette entrée ? Cette action est définitive.'))return;const {error}=await sb.from(table).delete().eq('id',b.dataset.del);if(error){alert('Échec : '+error.message);return;}await renderData(table,title);});}
async function start(){if(page==='index.html'||page===''){login();return;}const {data:{user},error}=await sb.auth.getUser();if(error||!user){location.href='index.html';return;}let p;try{p=await getProfile(user);}catch(e){shell('Accès non configuré','Le compte est connecté, mais son profil n’est pas accessible.',`<div class="notice error">${esc(e.message)}</div>`);return;}if(!p.active||p.access_status!=='active'){shell('Accès en attente','Ton profil doit être activé par un gérant.',`<div class="notice error">Statut : ${esc(p.access_status||'inconnu')}</div>`);return;}const def=defs[page]||defs['dashboard.html'];shell(def[0],def[1],'<div class="card">Chargement…</div>');if(page==='dashboard.html'){const counts=await Promise.all(['profiles','school_classes','school_subjects','school_courses','school_clubs'].map(async t=>{try{return [t,(await listTable(t)).length]}catch{return [t,'—']}}));$('#app').innerHTML=`<div class="mh-cards">${counts.map(([t,n])=>`<a class="card" href="${({'profiles':'students.html','school_classes':'classes.html','school_subjects':'subjects.html','school_courses':'timetable.html','school_clubs':'clubs.html'})[t]}"><small>${esc(t.replace('school_','').replace('_',' '))}</small><strong>${n}</strong></a>`).join('')}</div><article class="card"><h2>Bienvenue, ${esc(p.full_name||'Administrateur')} !</h2><p>Le portail est relié au nouveau projet Supabase. Les données scolaires démarrent vides.</p><p class="muted">Les modules historiques absents du schéma V2 sont signalés comme désactivés au lieu de provoquer une erreur.</p></article>`;return;}await renderData(def[2],def[0]);}
document.addEventListener('DOMContentLoaded',()=>start().catch(e=>{console.error(e);document.body.innerHTML=`<main class="mh-main"><div class="notice error"><strong>Erreur de chargement</strong><p>${esc(e.message||e)}</p><button class="btn secondary" onclick="location.reload()">Réessayer</button></div></main>`}));
